./bin/Linux/main: src/*.cpp include/*.h
	mkdir -p bin/Linux
	g++ -std=c++11 -Wall -Wno-unused-function -g -I ./include/ -o ./bin/Linux/main src/main.cpp src/glad.c src/Camera.cpp src/Game.cpp src/Input.cpp src/Model.cpp src/Shader.cpp src/Window.cpp src/tiny_obj_loader.cpp src/matrices.cpp src/Texture.cpp src/stb_image.cpp src/collisions.cpp src/textrendering.cpp ./lib-linux/libglfw3.a -lrt -lm -ldl -lX11 -lpthread -lXrandr -lXinerama -lXxf86vm -lXcursor

.PHONY: clean run
clean:
	rm -f bin/Linux/main

run: ./bin/Linux/main
	cd bin/Linux && ./main
